name: Trigger auto deployment for transcription-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/transcription-backend-AutoDeployTrigger-aff60e29-d540-4420-97b9-614424230db0.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TRANSCRIPTIONBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TRANSCRIPTIONBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TRANSCRIPTIONBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: newsarcscrapercontainerregistry.azurecr.io
          registryUsername: ${{ secrets.TRANSCRIPTIONBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TRANSCRIPTIONBACKEND_REGISTRY_PASSWORD }}
          containerAppName: transcription-backend
          resourceGroup: transcription
          imageToBuild: newsarcscrapercontainerregistry.azurecr.io/transcription-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


